DROP TABLE IF EXISTS PATIENT;

CREATE TABLE PATIENT(PATIENTNUMBER INT, PATIENTLASTNAME VARCHAR(20), PATIENTFIRSTNAME VARCHAR(20), PHONE VARCHAR(20), CITY VARCHAR(20), STREETNAME VARCHAR(20), COUNTRY VARCHAR(20));

INSERT INTO PATIENT (PATIENTNUMBER, PATIENTLASTNAME, PATIENTFIRSTNAME, PHONE, CITY, STREETNAME, COUNTRY) VALUES (0001, 'Amarasiri', 'Evanthika', '+94773636352', 'Galle Road', 'Colombo 03', 'Sri Lanka');
INSERT INTO PATIENT (PATIENTNUMBER, PATIENTLASTNAME, PATIENTFIRSTNAME, PHONE, CITY, STREETNAME, COUNTRY) VALUES (0002, 'Fernando', 'Senaka', '+94777112987', 'Je-ela', 'Temple Road', 'Sri Lanka');
INSERT INTO PATIENT (PATIENTNUMBER, PATIENTLASTNAME, PATIENTFIRSTNAME, PHONE, CITY, STREETNAME, COUNTRY) VALUES (0003, 'Hiranya', 'Hasitha', '+94771222922', 'Kandy', 'Radella', 'Sri Lanka');
INSERT INTO PATIENT (PATIENTNUMBER, PATIENTLASTNAME, PATIENTFIRSTNAME, PHONE, CITY, STREETNAME, COUNTRY) VALUES (0004, 'Madurangi', 'Pavithra', '+94772331922', 'Horana', '6th Street', 'Sri Lanka');
INSERT INTO PATIENT (PATIENTNUMBER, PATIENTLASTNAME, PATIENTFIRSTNAME, PHONE, CITY, STREETNAME, COUNTRY) VALUES (0005, 'Anuradha', 'Chamara', '+94773113871', 'Kegalle', '5th Lane', 'Sri Lanka');
