DROP DATABASE IF EXISTS medicaldb;
DROP USER 'patient'@'localhost';
DROP USER 'patient'@'%';

CREATE DATABASE medicaldb;
CREATE USER 'patient'@'localhost' IDENTIFIED BY 'wso2';
CREATE USER 'patient'@'%' IDENTIFIED BY 'wso2';
GRANT ALL PRIVILEGES ON medicaldb.* TO 'patient'@'localhost';
GRANT ALL PRIVILEGES ON medicaldb.* TO 'patient'@'%';

USE medicaldb;
DROP TABLE IF EXISTS patient;

CREATE TABLE `patient` (
                           `id` mediumint(8) unsigned NOT NULL auto_increment,
                           `number` mediumint,
                           `last_name` varchar(255) default NULL,
                           `first_name` varchar(255) default NULL,
                           `phone` varchar(100) default NULL,
                           `city` varchar(255),
                           `street` varchar(255) default NULL,
                           `country` varchar(100) default NULL,
                           PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;


INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (1,"Rhodes","Patrick","784-1683","Tracadie-Shelia","Ap #680-4971 Dictum Avenue","Kuwait");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (2,"Sears","Mariko","1-597-644-9325","Kearny","Ap #585-358 Diam Rd.","Togo");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (3,"Humphrey","Ima","1-842-895-9140","Brugge Bruges","Ap #514-3584 Luctus, Road","Mexico");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (4,"Rowland","Raphael","1-336-356-3271","Wichita","2402 Suspendisse Street","Djibouti");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (5,"Castaneda","Cherokee","734-8377","Duluth","Ap #982-5063 Magna, St.","Faroe Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (6,"Gates","Lucy","1-613-347-9902","Kilmalcolm","472 Sed Road","San Marino");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (7,"Cannon","Quynn","1-311-864-0993","Compiègne","Ap #184-8569 Integer Rd.","Guatemala");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (8,"Dyer","Gage","1-569-439-7341","Moerbeke","5482 Eget Av.","Spain");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (9,"Cross","Alexa","304-6431","Ruisbroek","P.O. Box 423, 5733 Magnis Rd.","Rwanda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (10,"Mcclure","Russell","1-471-754-9973","Butzbach","P.O. Box 411, 2413 Ultrices Rd.","Qatar");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (11,"Kennedy","Justin","245-0712","Strijtem","352-4280 Tempor Rd.","Korea, South");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (12,"Burton","Myra","672-1374","Columbia","2420 Aliquam Rd.","Albania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (13,"Oliver","Jasmine","1-209-502-5169","Opheylissem","890-8603 Donec St.","New Caledonia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (14,"Knox","Hoyt","423-0988","Londerzeel","Ap #357-8194 Eu Street","Costa Rica");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (15,"Torres","Sybill","276-3034","Reading","Ap #388-6110 Leo. Avenue","Guyana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (16,"Solis","Mannix","525-6781","Rijkevorsel","684-2364 Luctus St.","Palau");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (17,"Schultz","Constance","245-4493","Albisola Superiore","721-7436 Sed Street","Togo");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (18,"James","Michael","644-8483","Guna","5652 Lorem, Ave","Romania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (19,"Olson","Urielle","1-913-539-6166","Ludwigsfelde","577-5850 Ut Avenue","Palau");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (20,"Mejia","Yasir","1-733-188-1001","Anand","Ap #405-3253 Cras Rd.","Montserrat");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (21,"Ashley","Shaine","282-1707","San Joaquín","P.O. Box 724, 8098 Magna. Road","Denmark");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (22,"Rogers","Brock","1-681-992-7253","Villers-la-Bonne-Eau","P.O. Box 828, 5907 Imperdiet St.","Russian Federation");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (23,"Nelson","Giselle","450-0012","Orsogna","P.O. Box 439, 3096 Curae; Rd.","French Guiana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (24,"Bryan","Astra","1-769-821-4275","Logan City","Ap #527-6054 Nisi. Rd.","Netherlands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (25,"Moran","Daria","173-3546","Bo'ness","Ap #852-7398 Justo. Street","Kazakhstan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (26,"Gross","Doris","378-4403","Chandannagar","945-7710 Purus Street","Tanzania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (27,"Harper","Sandra","1-459-523-7408","Saint-Médard-en-Jalles","P.O. Box 291, 791 Non, St.","United States");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (28,"Humphrey","Ava","1-208-339-7828","Madurai","Ap #773-5047 Sapien Avenue","American Samoa");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (29,"Simmons","Sarah","754-8190","Greater Sudbury","Ap #181-3413 Aliquam Rd.","Haiti");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (30,"Shields","Victoria","802-3292","Blankenberge","Ap #351-8618 Fusce St.","United States Minor Outlying Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (31,"Gilliam","Wynne","1-658-496-6844","Toledo","8390 Varius. Ave","Namibia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (32,"Short","Xerxes","1-571-933-3003","Torgiano","572-6369 Et St.","Hungary");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (33,"Hendricks","Nasim","349-2841","Conchalí","3272 Elit. Avenue","Paraguay");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (34,"Gomez","Ruth","1-905-899-3361","Montefiore dell'Aso","Ap #874-2457 Arcu St.","Slovakia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (35,"Butler","Adara","1-128-256-0845","Neerglabbeek","2991 Ipsum Rd.","Georgia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (36,"Taylor","Breanna","1-266-522-9227","Sint-Martens-Bodegem","P.O. Box 661, 7976 Tortor. Rd.","Turks and Caicos Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (37,"Bradshaw","Colorado","1-969-929-2587","Ñiquén","908-1816 Dui. St.","Djibouti");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (38,"Schmidt","Macaulay","288-6653","Gattatico","672-3780 Blandit Rd.","Botswana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (39,"Dudley","Kyra","261-3878","Fresno","Ap #978-5063 Feugiat St.","France");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (40,"Norman","Roanna","231-7234","Wilmington","Ap #693-8870 Montes, Ave","Sierra Leone");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (41,"Mcgee","Naomi","1-998-567-4281","Schwalbach","947-546 Adipiscing Avenue","Macao");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (42,"Duffy","Hyatt","1-816-810-6238","Offenburg","135-7781 Lorem, Road","Latvia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (43,"Reynolds","Daphne","1-996-566-1213","Ofena","Ap #686-6882 Lobortis Road","Vanuatu");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (44,"Haney","Rose","253-3828","Quellón","1785 Non, Rd.","Philippines");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (45,"Kramer","Duncan","890-9136","Lairg","P.O. Box 772, 7731 Mollis Avenue","Jordan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (46,"Pugh","Alvin","655-4281","Kitimat","P.O. Box 530, 3596 Nulla St.","Malawi");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (47,"Jarvis","Sacha","1-194-787-3743","Duluth","P.O. Box 115, 9536 Euismod Rd.","Saint Lucia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (48,"Patrick","Dacey","423-8489","Saint-Georges","422-9812 Vulputate St.","Ireland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (49,"Walter","Karly","754-0809","Rio Marina","P.O. Box 396, 5014 Erat Avenue","Nepal");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (50,"Fulton","Roanna","1-775-518-7399","Gliwice","Ap #399-8018 Interdum Road","Curaçao");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (51,"Buchanan","Naomi","126-6344","Evesham","P.O. Box 516, 184 Mauris Ave","Papua New Guinea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (52,"Clark","Ignatius","911-8856","100 Mile House","902-7059 Nisi. Ave","Gabon");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (53,"Pope","Xaviera","1-860-961-0827","Essex","7719 Integer Av.","Malta");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (54,"Daniel","Igor","487-9891","San Giovanni Lipioni","5588 Aenean Av.","Cambodia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (55,"Snyder","Lee","743-3095","Thanjavur","P.O. Box 929, 223 Nisl. Avenue","Armenia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (56,"Carter","Brendan","748-9399","Birmingham","410-7181 Lectus St.","Viet Nam");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (57,"Wall","Buffy","527-0593","Armadale","7567 Elementum, St.","Mali");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (58,"Cotton","Larissa","202-8624","Glossop","7592 Purus, Rd.","Nauru");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (59,"Guerra","Victoria","1-637-497-2564","Ararat","P.O. Box 901, 7984 Sit Road","Bolivia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (60,"Coleman","Tana","951-4419","Slough","9031 In Rd.","Uganda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (61,"Whitehead","Kylan","1-253-247-4892","Detroit","Ap #853-9046 Nulla St.","Austria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (62,"Rose","Miriam","1-920-990-7103","Waret-l'Evque","514-9919 Vel, Avenue","Algeria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (63,"Galloway","Malcolm","578-3786","Silvassa","Ap #283-2127 Eu Ave","New Zealand");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (64,"Little","Christopher","1-538-870-0608","Buckingham","2394 Purus Rd.","Malaysia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (65,"Vance","Rebecca","1-685-593-3422","Mirzapur-cum-Vindhyachal","335-1636 Nam Rd.","Jersey");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (66,"Gutierrez","Whitney","1-796-240-8122","Valparaíso","Ap #512-2542 Mauris St.","Libya");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (67,"Cabrera","Carla","324-1522","Quintero","1180 Sem Rd.","Sudan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (68,"England","Caryn","1-914-212-5921","Kharagpur","410 Arcu St.","South Sudan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (69,"Atkins","Martina","1-711-511-1432","Sannazzaro de' Burgondi","2272 At Av.","Cameroon");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (70,"Branch","Troy","1-869-382-0350","Quinta de Tilcoco","950-1864 Neque Av.","Singapore");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (71,"Hamilton","Regan","1-804-624-7487","Itterbeek","P.O. Box 133, 7588 Porttitor Avenue","Armenia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (72,"Reeves","Zahir","1-933-160-5489","Portofino","Ap #668-8209 Cursus St.","Spain");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (73,"Boyle","Keaton","1-840-788-4160","Cuceglio","P.O. Box 721, 9002 Sed, Ave","Martinique");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (74,"Houston","Vernon","1-399-151-0041","Georgia","805-1553 Id Av.","Kazakhstan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (75,"Owens","Rachel","1-470-536-8383","Kawawachikamach","P.O. Box 520, 4280 Ac Street","Uruguay");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (76,"Meyer","Carl","211-3579","Wabamun","P.O. Box 677, 5058 Luctus. St.","Laos");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (77,"House","Whilemina","250-8618","Ponoka","Ap #226-9858 Enim, St.","Honduras");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (78,"Burnett","Rose","765-9755","Martigues","P.O. Box 738, 8753 In Road","Anguilla");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (79,"Taylor","Remedios","1-726-244-8599","San Pancrazio Salentino","Ap #723-1129 Cursus Rd.","Hungary");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (80,"Olsen","Zahir","139-8635","Chimbarongo","103 Sed Road","Wallis and Futuna");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (81,"Walters","Wing","352-4466","Bharatpur","994 Malesuada Ave","Hungary");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (82,"Day","Kylee","370-8238","Chonchi","2818 Venenatis Street","Iran");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (83,"Gutierrez","Olympia","1-978-404-4293","HomprŽ","Ap #455-9803 Lobortis Ave","Antigua and Barbuda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (84,"Hughes","Kylie","407-6529","Falerone","900-6788 Quisque St.","Sint Maarten");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (85,"George","Kerry","364-1841","Bergama","Ap #356-982 Felis. Rd.","Libya");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (86,"Schultz","Carly","1-750-537-3726","Columbus","7797 Augue Rd.","Faroe Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (87,"Gay","Quynn","1-443-108-1782","Miramichi","Ap #890-2470 Nunc St.","Guernsey");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (88,"Solis","Levi","260-7989","East Kilbride","Ap #818-2985 A, Road","Bosnia and Herzegovina");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (89,"Rosa","Iona","206-0772","Edmundston","5536 Neque. Avenue","Norway");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (90,"Vega","Damian","512-3858","Markham","231-3492 A St.","Tanzania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (91,"Weiss","Carissa","1-883-253-3286","Masullas","1574 Mus. Avenue","Taiwan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (92,"Horn","Ignatius","1-208-658-8648","Halifax","384-7516 Vestibulum Av.","Turkmenistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (93,"Bates","Kylee","1-731-323-0226","Steenokkerzeel","673-7291 Arcu. Road","Grenada");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (94,"Kim","Otto","616-1969","Bouffioulx","Ap #846-1108 Eu Road","Zambia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (95,"Wilkinson","Mark","1-598-742-7280","Gandhidham","P.O. Box 231, 2020 Id St.","Uzbekistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (96,"Adkins","Zoe","1-876-879-5799","Cork","664-6468 Metus. Ave","Turkey");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (97,"Justice","Allegra","1-963-113-4732","Nanaimo","P.O. Box 983, 444 Proin Road","Senegal");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (98,"Jones","Amela","1-598-360-6465","Prince Albert","4671 Auctor Rd.","Mauritania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (99,"Crosby","Aaron","706-0601","Smithers","433-3627 Lectus Rd.","Liechtenstein");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (100,"Phelps","Jordan","625-9411","Martello/Martell","515-8224 Arcu. Road","Sudan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (101,"Roach","Robin","1-330-153-2985","Masone","6177 Suspendisse Rd.","Costa Rica");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (102,"Mills","Dominic","1-705-161-1174","Kemzeke","Ap #592-545 At, Road","Togo");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (103,"Hurst","Dillon","1-624-695-5768","Bon Accord","284-8328 Gravida St.","Mexico");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (104,"Mejia","Yen","1-191-913-8199","B.S.D.","Ap #672-5974 Nunc Rd.","Pakistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (105,"Jackson","Linda","558-3238","Gulfport","P.O. Box 705, 8961 Pede Rd.","Bhutan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (106,"Martin","Savannah","1-576-198-4690","Dilbeek","4713 Suspendisse Road","Portugal");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (107,"Gutierrez","Rowan","1-639-594-7091","Mont-Saint-Guibert","P.O. Box 618, 2732 Tellus, St.","Benin");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (108,"Graves","Nita","274-7452","Camerino","P.O. Box 377, 2205 Donec St.","Nepal");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (109,"Monroe","Karly","1-674-294-9402","Val Rezzo","Ap #324-4636 At St.","Sierra Leone");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (110,"Velasquez","Barry","179-2548","Rum","P.O. Box 742, 8935 In Av.","Lesotho");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (111,"Stephenson","Berk","1-407-329-4580","Picton","9530 Nunc St.","Montenegro");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (112,"Richard","Ali","1-493-236-8837","Tczew","209-9772 Fermentum Rd.","Bhutan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (113,"Graves","Georgia","1-829-220-8096","Berhampore","187-9392 Sodales Rd.","Sint Maarten");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (114,"Morgan","Irma","518-9109","Ketchikan","Ap #456-9875 Donec St.","Tanzania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (115,"Moran","Eleanor","1-289-423-1950","Sachs Harbour","461-5167 Mi, Road","Saint Lucia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (116,"Obrien","Rafael","1-850-204-0775","Castellafiume","1779 At Ave","Burundi");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (117,"Hale","Orli","1-316-481-9340","Montes Claros","P.O. Box 624, 7886 A, Avenue","Cyprus");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (118,"Hess","Kirk","1-730-811-6717","Geesthacht","542-7236 Cursus, Street","Korea, North");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (119,"Herman","Hector","652-2942","Gmunden","Ap #403-1238 Integer Avenue","Taiwan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (120,"Luna","Colorado","646-4319","Vergemoli","Ap #357-3578 Ligula. Avenue","Cyprus");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (121,"Norris","Kirby","839-8591","Enna","Ap #199-1643 Duis Street","Albania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (122,"Crosby","Stephanie","910-6891","Mjölby","1043 Urna Street","Morocco");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (123,"Sexton","Iris","1-627-698-2186","Buckingham","P.O. Box 409, 4137 Erat, Road","Ireland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (124,"Mullins","Harper","1-188-341-4007","Soissons","5421 Orci, Street","French Southern Territories");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (125,"Oneal","Fritz","265-7885","Bharuch","Ap #122-7053 Placerat, Avenue","Andorra");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (126,"Harvey","Rooney","666-1201","Dipignano","Ap #470-3001 Volutpat Ave","Niue");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (127,"Peterson","Rachel","1-145-707-8317","Kapuskasing","6220 Tellus Rd.","Kiribati");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (128,"Todd","Price","1-507-679-1362","Vegreville","P.O. Box 590, 6666 Aliquet St.","Guinea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (129,"Fernandez","Ezra","1-348-381-6669","Alanya","691-4312 Integer St.","Nepal");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (130,"Battle","Knox","889-6378","Tilburg","968-8616 In, St.","Yemen");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (131,"West","Amy","692-0000","Brandon","3116 Lorem. Rd.","Vanuatu");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (132,"Harris","Jameson","499-9482","O'Higgins","Ap #211-381 Lorem, Ave","Korea, North");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (133,"Barnett","Sacha","1-284-735-1530","Nocera Umbra","P.O. Box 384, 6464 Tellus. Avenue","Macedonia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (134,"Conway","Carol","199-1950","Opprebais","8681 Lobortis, Rd.","Mali");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (135,"Pearson","Adena","715-5246","Sesto Campano","Ap #148-6541 Eget Rd.","Bosnia and Herzegovina");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (136,"Owen","Francesca","582-0813","Swan","Ap #816-3402 Senectus Rd.","Germany");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (137,"Hanson","Patricia","658-6451","Rotorua","8469 At Rd.","French Guiana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (138,"Barton","Kenneth","810-5427","Isca sullo Ionio","967 Aliquam Av.","Saint Martin");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (139,"Kinney","Rose","1-694-219-4414","Limón (Puerto Limón)","4705 Iaculis St.","Pakistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (140,"Klein","Cally","897-1393","Kırıkhan","Ap #512-2851 Pellentesque St.","Tonga");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (141,"Madden","Victor","196-2035","Windsor","3434 Et Road","Cayman Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (142,"Calhoun","Naomi","703-5415","Arnesano","Ap #688-2720 Mauris St.","Austria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (143,"Shepherd","Macaulay","752-7178","Arbroath","974-7377 Arcu. Road","Norfolk Island");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (144,"Rutledge","Maryam","533-9685","Sint-Stevens-Woluwe","7198 Tellus Avenue","United Arab Emirates");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (145,"Frank","Daquan","1-498-660-4495","Donstiennes","P.O. Box 272, 8380 Arcu. Rd.","Northern Mariana Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (146,"Downs","Quincy","832-1739","Besançon","8007 Augue Av.","Gambia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (147,"Allen","Harrison","971-2057","Oviedo","1693 Morbi St.","French Guiana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (148,"Woodward","Emma","682-4368","Wels","982-6232 Donec Rd.","Chad");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (149,"Joyner","Justine","311-3411","Quilleco","340-6629 Pede. St.","Philippines");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (150,"Hampton","Nathaniel","1-112-770-6080","Montague","P.O. Box 845, 9335 Habitant Rd.","Chile");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (151,"Dillon","Jesse","890-1032","Hereford","383-2931 Sapien Av.","Montenegro");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (152,"Gates","Carson","499-3044","Chaitén","P.O. Box 921, 4774 Sagittis. Av.","Slovakia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (153,"Mays","Hector","1-160-819-9484","Ergani","P.O. Box 875, 8443 Pharetra. St.","Albania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (154,"Cooley","Anthony","772-7519","San Martino in Badia/St. Martin in Thurn","P.O. Box 936, 1253 Velit Av.","Kenya");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (155,"Hooper","Lillith","1-334-259-6539","Pretoro","754-4375 Nunc Rd.","Panama");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (156,"Maxwell","Kibo","1-381-485-7968","Pica","Ap #706-1188 Integer Ave","Guatemala");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (157,"Lynch","Nita","832-9663","Huntingdon","767-5655 Quis St.","Sierra Leone");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (158,"Patterson","Zephania","1-207-361-7224","Kailua","890-5316 Accumsan Ave","Andorra");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (159,"Cantrell","Rebecca","780-1263","Chestermere","866-4348 Lorem St.","Martinique");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (160,"Head","Guy","1-515-250-1032","Recco","Ap #195-5783 Mi Ave","Liberia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (161,"Tanner","Fulton","1-231-142-1311","Hatfield","Ap #526-3801 Congue Street","Australia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (162,"Whitney","Rhoda","1-263-250-3110","South Bend","2993 Etiam St.","Slovenia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (163,"Saunders","Eleanor","172-1651","Lokeren","Ap #194-7477 Ac St.","Virgin Islands, British");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (164,"Aguilar","Katell","1-991-312-0657","Inverurie","4364 Vestibulum. St.","Monaco");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (165,"Gould","Abraham","1-477-800-3493","Uberlândia","P.O. Box 823, 2421 Erat Rd.","Saint Helena, Ascension and Tristan da Cunha");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (166,"Robbins","Chastity","921-7521","Vernon","758-5243 Parturient Street","Isle of Man");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (167,"Spears","Abbot","304-7354","Purranque","735-720 Metus Av.","Saint Helena, Ascension and Tristan da Cunha");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (168,"Workman","Ethan","1-894-998-0747","Castelbuono","2115 Magna, Ave","Kazakhstan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (169,"Briggs","Kirsten","1-310-221-3726","Skövde","P.O. Box 394, 6926 Mauris Ave","Antigua and Barbuda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (170,"Pugh","Priscilla","1-343-153-9035","Steenokkerzeel","P.O. Box 314, 9371 Pretium Rd.","Belize");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (171,"Quinn","Frances","782-9919","Mejillones","408-4266 Et Street","Solomon Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (172,"Britt","Uriel","1-172-912-3409","Sluizen","4955 Curabitur Rd.","Zimbabwe");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (173,"Strickland","Hasad","1-758-948-2107","Junagadh","Ap #320-8344 Tempor St.","India");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (174,"Briggs","TaShya","1-874-421-3151","Los Muermos","P.O. Box 209, 4663 Erat Avenue","Isle of Man");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (175,"Morton","Tiger","1-713-877-5472","Pozantı","786-5373 Non Street","Germany");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (176,"Huff","Dylan","832-0848","Bergisch Gladbach","P.O. Box 788, 4774 Suspendisse Avenue","Angola");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (177,"Hamilton","Quin","138-6783","Dresden","Ap #568-1921 Lacus. Avenue","Viet Nam");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (178,"Maddox","Renee","1-577-840-8759","Panihati","470-6267 Hymenaeos. St.","Guinea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (179,"King","Merritt","536-6440","Virginal-Samme","P.O. Box 741, 4557 Suspendisse Road","Guatemala");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (180,"Pickett","Hadley","1-252-713-9112","Bussolengo","5351 Tempus Street","Saint Pierre and Miquelon");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (181,"Curtis","Moana","1-682-348-0119","La Valle/Wengen","183-806 Aliquam Street","Latvia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (182,"Brennan","Linus","1-298-392-8671","Hoofddorp","Ap #388-756 Sodales Street","Sint Maarten");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (183,"Clayton","John","406-7596","Bondo","490-9593 Ornare, St.","Croatia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (184,"Ryan","Risa","691-4139","Santa Maria a Monte","881-8234 Ut Rd.","Bulgaria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (185,"Jimenez","James","1-108-229-5945","Momignies","Ap #837-5208 Sapien. St.","Heard Island and Mcdonald Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (186,"Lane","Diana","111-9269","New Westminster","P.O. Box 161, 5608 Eget, Rd.","Sint Maarten");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (187,"Fields","Autumn","1-164-956-9859","Belsele","Ap #790-617 Mauris St.","Gibraltar");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (188,"Miles","Camilla","793-1936","San Antonio","194 Ipsum. St.","Slovakia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (189,"Prince","Jared","1-871-844-3181","Meerhout","Ap #934-8879 Sed Rd.","Zambia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (190,"Johnson","Rhonda","1-152-396-0974","Wedel","Ap #999-4489 Iaculis Rd.","Saint Martin");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (191,"Cash","Brady","1-195-154-7990","Laces/Latsch","6760 Sodales Rd.","Ghana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (192,"Valdez","Galena","1-130-680-9887","Douai","Ap #443-6557 Nibh. Rd.","Qatar");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (193,"Cook","Phyllis","104-8317","Chartres","Ap #312-3919 Vivamus Road","Andorra");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (194,"Galloway","Barrett","1-812-626-2058","Loy","P.O. Box 123, 735 Ultrices Av.","Congo (Brazzaville)");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (195,"Mueller","Bo","1-329-747-4942","Stockerau","632 Molestie Avenue","Namibia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (196,"Santana","Conan","391-0191","La Matap�dia","P.O. Box 216, 7371 Orci. Avenue","Sint Maarten");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (197,"Kim","Jesse","852-5583","Des Moines","671 Donec Rd.","Latvia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (198,"Small","Bethany","1-819-391-7254","Pukekohe","Ap #538-2067 Vitae Rd.","Latvia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (199,"King","Regina","386-8184","Allein","P.O. Box 136, 8939 Magna Rd.","New Zealand");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (200,"Sandoval","Slade","1-777-719-7628","Messancy","P.O. Box 306, 5771 Ac Rd.","Germany");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (201,"Sloan","Rachel","811-5373","Bhuj","829-1840 Mauris St.","Niger");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (202,"Chang","Jennifer","1-510-414-2412","Mühlheim am Main","560-3010 Eu St.","Heard Island and Mcdonald Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (203,"Curry","Lucian","655-4756","Tiarno di Sopra","P.O. Box 335, 2785 Dolor Road","Nicaragua");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (204,"Espinoza","Brennan","854-6761","Calvello","P.O. Box 393, 2556 Malesuada St.","Senegal");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (205,"Oconnor","Patricia","1-575-701-7375","Anzi","6659 Fusce Rd.","Denmark");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (206,"Taylor","Faith","1-743-676-6842","Tofield","9253 Mus. Avenue","Czech Republic");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (207,"Huff","Ezra","221-6567","Paignton","Ap #646-1917 Dui, Avenue","Heard Island and Mcdonald Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (208,"Lynch","Ursa","164-8820","Bo'ness","Ap #340-4163 Cras Street","Montenegro");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (209,"Spencer","Regina","575-4656","Bridge of Allan","P.O. Box 268, 5676 Nulla Av.","Cocos (Keeling) Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (210,"Lawson","Ginger","240-3717","Kerkhove","870 Lorem, Road","Macedonia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (211,"Aguirre","Patience","1-519-696-5164","Meugliano","P.O. Box 829, 8295 Eu Ave","Uzbekistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (212,"Fuentes","Adena","1-755-349-7673","Jaranwala","Ap #260-7858 Ipsum Av.","Anguilla");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (213,"Ramos","Adam","1-695-554-3811","Pinto","Ap #716-5592 Fringilla Av.","Bolivia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (214,"Hoffman","Kiona","774-7613","Thiaumont","696-3183 Sed Av.","Suriname");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (215,"Burgess","Oliver","748-6213","Millet","964-4233 Venenatis Av.","Fiji");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (216,"Cervantes","Eliana","1-270-483-3738","Thurso","P.O. Box 821, 1111 Molestie Av.","Côte D'Ivoire (Ivory Coast)");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (217,"Middleton","Vivien","1-520-672-2857","Bernau","4021 Tellus. St.","Bolivia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (218,"Spence","Haviva","1-860-556-1811","Goderich","359-2730 Nunc Av.","Comoros");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (219,"Collins","Samuel","775-1277","Inveraray","8632 Nunc Rd.","Malaysia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (220,"Landry","Destiny","795-8855","Auldearn","716-5803 Arcu. Avenue","Switzerland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (221,"Garza","Oleg","1-607-813-4192","Columbus","Ap #796-5637 Diam Avenue","Nepal");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (222,"Bates","Finn","818-7102","Bayonne","P.O. Box 520, 5717 Quisque Av.","Andorra");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (223,"Baxter","Savannah","1-734-737-1523","Mumbai","Ap #678-7656 Dui Rd.","Somalia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (224,"Sellers","Scarlet","1-680-146-7615","Midway","792-8509 Mauris Street","Germany");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (225,"Henderson","Karly","911-6343","San Venanzo","Ap #782-4360 Amet Rd.","Guatemala");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (226,"Cantu","Wilma","1-936-138-0278","Price","8889 Adipiscing Av.","Albania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (227,"Hudson","Rina","1-882-700-0192","Penrith","P.O. Box 761, 8369 Dolor Road","Greece");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (228,"Buchanan","Wayne","1-434-314-0135","Marabá","P.O. Box 295, 9290 Gravida Street","Guam");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (229,"Booth","Driscoll","1-255-961-3217","Bulandshahr","5154 Pede, Rd.","Bolivia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (230,"Sloan","Alana","1-875-549-7448","João Pessoa","134-5414 Sed Av.","Martinique");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (231,"Wilder","Daquan","1-157-647-3929","Bertiolo","906-5158 Nec St.","Uruguay");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (232,"Kirkland","Clark","1-630-360-2364","Barranca","Ap #595-8489 Ut Rd.","Taiwan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (233,"Barnett","Alisa","1-413-720-1210","Brandon","3228 Sit Avenue","Cuba");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (234,"Hooper","Donovan","331-5680","Laguna Blanca","P.O. Box 465, 7397 Facilisis Road","Guernsey");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (235,"Shelton","Stuart","535-3948","Burgos","8149 Eros Rd.","Niue");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (236,"Mcgowan","Hadassah","490-2457","Ilhéus","897-2153 Magna. Road","San Marino");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (237,"Mays","Teegan","804-8141","Huissen","1055 Dictum Road","Guadeloupe");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (238,"Horne","Upton","952-0214","Idaho Falls","2375 Nulla. St.","Burundi");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (239,"Noble","Hollee","1-745-114-8496","Kalgoorlie-Boulder","7725 Quam, Avenue","Gambia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (240,"Hale","Naida","1-683-750-7729","Sciacca","240-7107 Sociis Road","Bhutan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (241,"Bailey","Oren","1-274-204-1356","Forst","Ap #783-5622 Aliquam Av.","Bahrain");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (242,"Conway","Amena","679-1575","Chapra","Ap #658-3370 Mauris Rd.","Dominican Republic");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (243,"Collins","Autumn","1-881-361-2386","Buxton","771-6984 Ullamcorper Road","United States");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (244,"Mills","Summer","343-5550","Ödemiş","Ap #730-6150 Ac Rd.","Zambia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (245,"Huber","Yael","897-9462","Patna","P.O. Box 265, 1867 Pellentesque Road","Armenia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (246,"Kline","Kevyn","380-7904","Bierges","P.O. Box 396, 4147 Tortor. St.","Guyana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (247,"Bernard","Geraldine","1-140-124-5472","Norman","9924 Ornare Rd.","United Kingdom (Great Britain)");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (248,"Ashley","Rebecca","576-7007","Nieuwerkerken","P.O. Box 487, 1218 Augue Street","Grenada");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (249,"Rosa","Idola","1-133-155-2275","Pau","6679 Eu Rd.","Viet Nam");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (250,"Coleman","Theodore","1-776-384-0222","Muzaffarpur","4861 Enim Street","Cape Verde");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (251,"Barber","Raymond","771-5984","Poviglio","P.O. Box 258, 1767 Urna Rd.","Benin");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (252,"Guzman","Wyoming","1-420-116-3072","High Level","7825 Netus Av.","Turkey");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (253,"Gould","Joan","337-4587","Metz","Ap #320-1363 Arcu. St.","Bhutan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (254,"Mcgowan","Thor","1-682-617-9337","Marystown","914-4292 Lobortis Ave","Barbados");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (255,"Herring","Imogene","863-4618","Sant'Eusanio Forconese","3011 Mauris Street","Philippines");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (256,"Donovan","Amy","1-195-632-3772","Lakeshore","355 Diam. Rd.","Moldova");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (257,"Brennan","Brenden","133-7520","Termes","7319 Conubia Rd.","Italy");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (258,"Burgess","Whitney","597-9075","Beaufays","Ap #776-7393 Mi Ave","Eritrea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (259,"Rosa","Jamal","795-8777","Lloydminster","P.O. Box 491, 4641 Vel, Ave","Djibouti");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (260,"Guerra","Abbot","706-1157","Lac La Biche County","3442 Ullamcorper. St.","Norway");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (261,"Reilly","Bruce","921-8559","San Polo d'Enza","637-2424 Varius. Avenue","Estonia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (262,"Tyson","Xaviera","563-9998","Nacimiento","Ap #202-8626 Sem, Ave","Heard Island and Mcdonald Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (263,"Barrett","McKenzie","1-160-487-4608","Quedlinburg","9545 Donec St.","Guadeloupe");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (264,"Crosby","Velma","338-1783","Lompret","Ap #415-6026 Eget Street","Sierra Leone");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (265,"Levy","Jael","1-209-745-9008","Zoetermeer","963-3774 Mauris Avenue","Iran");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (266,"Fields","Rosalyn","928-7832","Glendale","Ap #799-8545 Proin Road","Nauru");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (267,"Cantu","Malik","1-861-234-3665","Township of Minden Hills","Ap #418-7603 Mus. Street","New Caledonia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (268,"Massey","Jennifer","354-5073","Saint-Servais","4261 Cursus St.","Libya");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (269,"Alford","Lance","1-865-529-1037","Bolzano/Bozen","7293 Id Rd.","Central African Republic");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (270,"Allison","Hunter","1-881-656-6760","Oostmalle","578-3609 Nisi. Road","Czech Republic");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (271,"Decker","Shellie","1-998-347-7947","Castelnuovo Magra","479-6780 Porttitor Road","Nauru");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (272,"Dixon","Dominique","1-113-188-6347","Purmerend","4446 Ac Rd.","Zimbabwe");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (273,"Sanders","Aiko","195-9408","Fairbanks","Ap #842-8153 Consequat, St.","Spain");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (274,"Morton","Lewis","727-7962","Medicine Hat","P.O. Box 194, 7046 Consectetuer Rd.","Micronesia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (275,"King","Tyrone","1-117-233-3489","San Massimo","P.O. Box 562, 2703 Nulla Street","United Arab Emirates");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (276,"Walsh","Beau","1-418-213-5584","Pietragalla","743-6684 Vehicula St.","Mozambique");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (277,"Sanchez","Amaya","1-530-665-5790","Bredene","417 Faucibus St.","Gibraltar");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (278,"Cash","Damian","1-680-913-8491","Sudbury","754-4749 Fringilla Rd.","Brazil");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (279,"Beck","Xavier","1-904-618-7461","Valverde","P.O. Box 598, 7520 Duis St.","Chile");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (280,"Nichols","Ingrid","424-0624","Korbach","P.O. Box 965, 8405 Dignissim St.","Heard Island and Mcdonald Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (281,"Shields","Athena","717-5623","Macchia Valfortore","959-4201 Pellentesque Rd.","Cyprus");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (282,"Drake","Brielle","1-706-897-0444","Tofield","P.O. Box 309, 7226 Molestie Street","Oman");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (283,"Munoz","Martina","1-544-492-1278","Whyalla","Ap #140-6098 Sem Av.","Uganda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (284,"Vance","Haviva","928-4691","Dave","3956 Nec, Av.","Ecuador");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (285,"Cline","Anastasia","351-5754","Tambaram","Ap #162-9363 Donec Rd.","Seychelles");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (286,"Riley","Libby","184-3744","Getafe","Ap #147-1351 Rutrum Street","French Guiana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (287,"Taylor","Peter","298-8992","Hattem","Ap #548-9732 Sed Av.","Ireland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (288,"Swanson","Hunter","1-184-834-5893","Ravensburg","Ap #195-8745 Mattis. St.","Algeria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (289,"Mcgee","Cade","1-275-307-1404","Grangemouth","4597 Nec Road","Maldives");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (290,"Moon","Isadora","115-0014","Amqui","3711 Donec St.","Philippines");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (291,"Rogers","Kyra","1-585-491-4585","Tavier","1603 In St.","Iran");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (292,"Gonzalez","Zachary","1-889-956-0929","Bhiwani","Ap #532-2583 Rutrum. Street","Burundi");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (293,"Ruiz","Jaden","1-292-506-4937","Saint-Mard","P.O. Box 955, 5674 Habitant St.","Cuba");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (294,"Whitney","Olympia","1-270-982-5030","Ceppaloni","8188 Fusce Rd.","Cape Verde");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (295,"Macias","Hayley","1-186-598-9222","My","Ap #470-649 At Road","Israel");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (296,"Cole","Hamish","1-253-307-8027","Fort Wayne","615-1761 Suspendisse Avenue","Bulgaria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (297,"Galloway","Nigel","890-9224","Isola del Gran Sasso d'Italia","2111 Orci, Street","Russian Federation");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (298,"Burton","September","504-9367","Oromocto","P.O. Box 277, 5325 Ac Avenue","Saint Vincent and The Grenadines");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (299,"Rice","Medge","1-808-123-1900","Barrhead","687-3206 Magna. Rd.","Haiti");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (300,"Neal","Chester","447-5051","Varsenare","602-4150 Sollicitudin St.","Bhutan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (301,"Mills","Cherokee","1-725-711-9656","San Demetrio Corone","P.O. Box 987, 5660 Lobortis St.","Nauru");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (302,"Duncan","Rosalyn","1-852-623-4499","Celle","P.O. Box 454, 3416 Orci. St.","Spain");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (303,"Francis","Chaney","1-359-191-3422","Fort Laird","Ap #907-4212 Nulla Rd.","Greenland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (304,"Knox","Hiram","519-0067","Cleveland","P.O. Box 646, 6198 Nunc Av.","Finland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (305,"Vargas","Jordan","1-172-256-2481","Salamanca","P.O. Box 166, 561 Faucibus Rd.","Georgia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (306,"Beasley","Kevyn","1-766-709-0382","Saltara","702-4636 Ac, Rd.","Bulgaria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (307,"Wells","Xerxes","1-976-939-4236","Bozeman","4936 Tempor St.","Poland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (308,"Hansen","Portia","1-188-818-4928","Lille","Ap #629-3107 Convallis Av.","Bonaire, Sint Eustatius and Saba");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (309,"Sargent","Melodie","674-9639","Heidelberg","P.O. Box 989, 7849 Ut Street","Brunei");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (310,"Walsh","Ramona","553-8673","Nieuwkapelle","P.O. Box 772, 9181 Dictum Avenue","Iran");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (311,"Kent","Hermione","1-320-973-6203","Kitchener","Ap #335-810 Aliquet Rd.","Mayotte");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (312,"Ball","Shannon","907-1818","Ñiquén","794-4491 Mattis Road","Paraguay");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (313,"Sexton","Orli","1-766-475-1582","Luton","338-5838 Neque Rd.","Saint Barthélemy");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (314,"Boone","Imogene","483-3780","Monceau-sur-Sambre","5358 Consectetuer Street","Congo (Brazzaville)");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (315,"Mcfarland","Stewart","357-3655","Sacramento","624-5992 Interdum. Rd.","Uzbekistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (316,"Branch","Rina","902-2862","Curicó","6539 Sed Av.","Philippines");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (317,"Welch","Remedios","1-988-865-3685","San Antonio","Ap #621-5547 Adipiscing Rd.","Sierra Leone");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (318,"Blanchard","Ivor","391-8128","Antofagasta","P.O. Box 242, 4301 Gravida St.","Vanuatu");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (319,"Brown","Faith","1-303-128-2310","Sennariolo","166-1104 Curabitur Street","Kuwait");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (320,"Gates","Alvin","1-429-188-8556","Sant'Agata Bolognese","388-8244 Sit St.","Eritrea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (321,"Barton","Karen","168-7370","Warrnambool","7222 Iaculis Rd.","South Africa");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (322,"Porter","Adrian","1-691-285-7377","Calle Larga","306-1194 Metus St.","Angola");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (323,"Joseph","Hasad","912-7874","Dillingen","Ap #984-2408 Purus. Avenue","Nicaragua");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (324,"Pitts","Serena","1-153-645-4278","Townsville","P.O. Box 491, 963 Mauris, Street","Algeria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (325,"Flores","Christian","219-2003","Henis","Ap #316-4794 Consectetuer Rd.","Rwanda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (326,"Gallagher","Kiayada","1-533-636-2654","Rankweil","P.O. Box 426, 1723 Dignissim Rd.","Cape Verde");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (327,"Le","Christopher","1-152-980-4104","Allappuzha","P.O. Box 883, 4138 Nunc Rd.","Uganda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (328,"Stevens","Lucy","1-418-912-6618","Minitonas","P.O. Box 460, 8904 Dictum. St.","Kiribati");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (329,"Reynolds","Alexis","862-7973","Wrigley","607-4944 Mauris Av.","Eritrea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (330,"Doyle","Chancellor","473-5265","Smoky Lake","P.O. Box 435, 6991 Quis St.","Saint Vincent and The Grenadines");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (331,"Campbell","Tamara","575-5841","Bilbo","286-6537 Enim Street","Costa Rica");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (332,"Bell","Yoko","1-762-584-0585","Kansas City","P.O. Box 793, 7288 In Rd.","Peru");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (333,"Cline","Sydney","841-0280","Newport News","515-3616 Dapibus St.","Montserrat");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (334,"Stark","Adam","1-580-317-4085","Kallo","P.O. Box 368, 6904 Ligula St.","Suriname");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (335,"Floyd","Hashim","1-755-175-0581","Sete Lagoas","669-1001 Ante Street","Bahamas");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (336,"Morse","Odette","1-977-589-7355","Nanton","Ap #601-828 Luctus Ave","Brunei");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (337,"Mayer","Quinn","1-939-948-3330","Birmingham","P.O. Box 870, 3944 Morbi St.","Slovakia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (338,"Small","Derek","853-1216","Stintino","P.O. Box 294, 3679 At Street","United Kingdom (Great Britain)");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (339,"Shaffer","Alana","1-583-466-8036","Mount Isa","Ap #673-1004 Eu Rd.","Indonesia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (340,"Mooney","Ulric","300-2654","Leduc","P.O. Box 322, 1949 Fringilla St.","Guinea-Bissau");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (341,"Sherman","Jaquelyn","1-869-517-4276","Pontey","P.O. Box 837, 3516 Nulla Street","Tonga");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (342,"Noel","Josephine","192-7886","Lac Ste. Anne","328-3343 Diam Rd.","Montenegro");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (343,"Reeves","Meredith","1-392-162-2700","Tarsia","P.O. Box 481, 3182 Elit Rd.","Malawi");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (344,"Bowers","Pamela","625-3406","Timkur","Ap #892-8335 Vulputate, St.","India");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (345,"Walter","Unity","552-2035","Bielefeld","Ap #308-7759 Luctus St.","Iraq");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (346,"Deleon","Leila","861-5297","Cinco Esquinas","6244 Nec, St.","Falkland Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (347,"Pate","Gwendolyn","1-550-473-6534","Zaria","7396 Quam, Rd.","Bulgaria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (348,"Sandoval","Quynn","992-8230","Montone","P.O. Box 499, 4033 Magna. Street","Pitcairn Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (349,"Gomez","Ayanna","588-0757","Cap-Rouge","379-9402 Ridiculus Road","Somalia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (350,"Parrish","Robin","181-0290","Canoas","681-1118 Nunc Avenue","Maldives");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (351,"Kelly","Herman","1-413-485-6502","Parkland County","P.O. Box 863, 6363 Semper. Rd.","Haiti");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (352,"Phillips","Mufutau","568-1536","Traiskirchen","P.O. Box 514, 5895 Ipsum Ave","Mali");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (353,"Byers","Odysseus","1-942-137-3036","Londerzeel","4970 Eu Ave","Iceland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (354,"Welch","Sonya","259-9398","Gallicchio","P.O. Box 400, 8481 Varius Ave","Fiji");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (355,"Dale","Phoebe","1-761-922-6339","Enna","978-7823 Pellentesque Avenue","Costa Rica");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (356,"Kirkland","Kathleen","792-6693","Marano Lagunare","P.O. Box 430, 9028 Dignissim Road","Gabon");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (357,"Joseph","Chaim","1-998-274-9315","Swan","Ap #865-2562 Molestie Rd.","Guinea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (358,"Jenkins","Valentine","795-8122","San Pedro de la Paz","Ap #240-6483 Molestie Avenue","Panama");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (359,"Flores","Ali","1-646-376-3694","Püttlingen","523-9273 Arcu Rd.","Bonaire, Sint Eustatius and Saba");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (360,"Robertson","Kellie","260-2643","Barrie","4823 Interdum Avenue","Uruguay");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (361,"Pace","Remedios","788-1150","Spremberg","Ap #345-2657 Dui, St.","British Indian Ocean Territory");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (362,"Santos","Lydia","243-9866","Champlain","Ap #712-3591 Malesuada St.","Vanuatu");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (363,"Burns","Paula","1-582-399-1772","Delta","P.O. Box 599, 9032 Libero. St.","Lithuania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (364,"Bowman","Clare","645-1785","Perchtoldsdorf","P.O. Box 127, 1985 Eget, Avenue","Czech Republic");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (365,"Gilliam","Emerson","1-955-626-9498","Sant'Arsenio","P.O. Box 243, 2349 Ac Street","Poland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (366,"Cobb","Keely","1-472-905-5341","Kingston","P.O. Box 706, 451 Ac, Avenue","Haiti");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (367,"Mccarthy","Iliana","1-573-790-1610","Ledeberg","6305 Sed Ave","Togo");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (368,"Sweet","Allen","101-8099","Innisfail","765-3192 Amet Street","Finland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (369,"Townsend","Medge","652-7710","Londrina","4590 Fusce Rd.","Curaçao");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (370,"Sloan","Nero","715-9419","St. Petersburg","121 Morbi Street","Angola");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (371,"Guerrero","Alden","734-5010","San Giuliano di Puglia","730-7430 Arcu Road","Bouvet Island");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (372,"Waters","Ira","637-5326","Dole","P.O. Box 336, 2727 Donec Rd.","Papua New Guinea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (373,"Jordan","Adam","936-2990","Bissegem","169-872 In, St.","Jersey");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (374,"Joyner","April","212-7694","Wernigerode","527-4172 Nunc Road","Laos");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (375,"Guerrero","Demetria","1-444-685-1910","Warszawa","7533 Mauris, Rd.","Seychelles");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (376,"Castro","Amelia","1-313-193-7175","Elversele","2495 Tempor Rd.","Bouvet Island");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (377,"Baldwin","Lara","315-3584","Tarvisio","Ap #628-6077 Non, Rd.","Montenegro");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (378,"Kerr","Raven","1-419-679-9597","Nelson","Ap #407-6007 Mauris St.","Antarctica");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (379,"Velazquez","Hanae","267-5950","Saint-GŽry","297-9140 Magna Rd.","French Polynesia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (380,"Cameron","Taylor","1-418-141-3939","Chillán Viejo","1522 Libero St.","Belarus");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (381,"Rowland","Roanna","881-4440","Malartic","P.O. Box 127, 7652 Facilisis. Ave","Åland Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (382,"Lynch","Karyn","1-773-669-4150","St. Albans","P.O. Box 102, 6733 Id Ave","Congo, the Democratic Republic of the");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (383,"Conway","Lillian","1-162-132-5757","Cagli","7201 Dolor Av.","Palau");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (384,"Davis","Kelly","1-443-944-5743","San Pedro de la Paz","626-5829 Ipsum Road","Mexico");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (385,"Dunlap","Jack","1-367-293-6746","Denbigh","Ap #947-2182 Erat. St.","Togo");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (386,"Harding","Caldwell","520-0925","Townsville","Ap #688-1697 Sed St.","Saint Lucia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (387,"Bush","Carl","1-515-234-7982","Gönen","Ap #336-9929 Rutrum Rd.","Macao");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (388,"Owens","Rhoda","1-757-617-4721","Tarsus","1713 Mollis Ave","Gabon");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (389,"Melton","Mechelle","670-2331","Linkhout","523-4661 Imperdiet Av.","Jordan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (390,"Moreno","Giselle","450-7151","Poole","P.O. Box 808, 6493 Nibh. Ave","Benin");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (391,"Patrick","Jack","815-6059","Llanwrtwd Wells","Ap #827-6989 Magna. Rd.","Peru");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (392,"Bradshaw","Stone","1-459-487-3919","Evansville","575-6197 Velit. Rd.","Qatar");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (393,"Randolph","Jarrod","1-138-436-9291","Albagiara","4734 Et, Av.","Egypt");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (394,"Austin","Ethan","979-1483","Lillianes","9323 Nec Road","Norway");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (395,"Cleveland","Kessie","1-882-488-6236","Caledon","6591 Ut Road","Suriname");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (396,"Barton","Odessa","1-572-326-8372","Montresta","P.O. Box 139, 376 A St.","Timor-Leste");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (397,"Finch","Tucker","517-8617","Southaven","362-7153 Dignissim St.","Norway");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (398,"Wallace","Hoyt","1-713-172-4397","Nagpur","Ap #495-4442 Orci Ave","Lithuania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (399,"Alexander","Teegan","696-8497","Coreglia Antelminelli","987-3356 Odio Av.","Sweden");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (400,"Bray","Kirk","1-827-397-2086","Asigliano Veneto","716 Diam. St.","Afghanistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (401,"Williamson","Marny","203-2564","Pemuco","Ap #707-7188 Mauris St.","Nauru");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (402,"Lewis","Simone","951-7492","Ottawa","603-1048 Libero. Ave","Nepal");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (403,"Conrad","Maisie","300-9584","San Maurizio Canavese","P.O. Box 472, 3243 Arcu St.","Macedonia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (404,"Talley","Sydney","547-3365","Pocatello","223-8021 Pede. Road","Namibia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (405,"Bonner","Alea","1-297-374-8610","Cumbernauld","3517 Ut, Av.","French Southern Territories");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (406,"Graves","Flavia","1-646-618-6741","Lake Cowichan","8625 Nunc Rd.","Macedonia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (407,"Patrick","Conan","1-409-569-5877","Montigny-lès-Metz","906-4032 Semper Rd.","Moldova");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (408,"Gamble","Maxwell","286-3694","Dampremy","P.O. Box 863, 1467 Convallis Rd.","Libya");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (409,"Walters","Beverly","1-933-297-3141","Gwalior","Ap #283-1543 Pede, St.","Colombia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (410,"Vance","Athena","1-842-763-0392","São José dos Pinhais","9420 Pede, Av.","Uganda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (411,"Rogers","John","1-520-614-0153","Saint-Pierre","5231 Risus Rd.","Virgin Islands, British");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (412,"Sexton","Ramona","916-6194","Haguenau","6552 Elementum St.","Sierra Leone");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (413,"Fitzpatrick","Shea","1-412-464-4275","Borgerhout","8568 Velit Street","Russian Federation");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (414,"Cochran","Paul","275-6741","Arrone","P.O. Box 483, 6319 Sem Rd.","Guinea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (415,"Dickson","Kitra","1-280-164-3672","Smoky Lake","260-1948 Vel, St.","Bahamas");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (416,"Simpson","Quamar","702-0859","Renfrew","320-1298 Venenatis Avenue","Bulgaria");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (417,"Sargent","Hall","475-1360","Watson Lake","1993 Donec Avenue","Canada");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (418,"Lancaster","Alexander","1-740-977-3374","West Ham","P.O. Box 232, 8864 Faucibus Avenue","Mexico");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (419,"Holmes","Cameron","238-4091","Melton","5750 Ultricies Road","Niger");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (420,"Jarvis","Clementine","352-7691","San José","P.O. Box 927, 3071 Arcu. Rd.","Bouvet Island");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (421,"Dillon","Macey","1-910-762-1767","Paris","Ap #179-5842 Fusce Avenue","Finland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (422,"Small","Caldwell","1-634-477-0167","Southwell","P.O. Box 299, 1103 Mauris St.","South Africa");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (423,"Willis","Levi","1-386-592-0612","Isca sullo Ionio","3772 Rutrum. Avenue","Equatorial Guinea");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (424,"Foster","Riley","1-827-782-9009","Thurso","Ap #804-4062 Ornare Street","Gibraltar");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (425,"Figueroa","Yuri","1-677-324-1074","San Mauro Cilento","Ap #275-1748 Magna St.","Saint Martin");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (426,"Thomas","Idola","1-396-323-1976","Ronciglione","P.O. Box 851, 1748 Aliquet. Road","Marshall Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (427,"Curry","Yvette","448-7147","Arvier","636-6804 Aliquam Av.","Greece");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (428,"Jensen","Daryl","283-6090","Irricana","P.O. Box 533, 1798 Dapibus Road","Turks and Caicos Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (429,"Branch","Kylee","149-6909","Nice","704-2977 Ornare Street","Bosnia and Herzegovina");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (430,"Skinner","Kameko","1-988-296-3400","Amravati","437-899 Magna Av.","Saint Barthélemy");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (431,"Farley","Caryn","1-814-618-6323","Pomarico","P.O. Box 727, 5611 Et Ave","Australia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (432,"Barton","Zephr","1-938-590-4100","Sunshine Coast Regional District","743-3242 Vitae Rd.","French Guiana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (433,"Mccray","Quail","1-694-104-0122","Dessau","Ap #940-8983 Erat Rd.","Mauritania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (434,"Duffy","Roary","639-1352","Warrnambool","Ap #482-2027 Sit Av.","Viet Nam");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (435,"Craig","Mark","373-1992","Spermalie","Ap #746-8600 Ornare Avenue","Yemen");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (436,"Hart","Jescie","1-436-415-0081","Zwijndrecht","Ap #983-8164 Vel Ave","Saint Barthélemy");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (437,"Owens","Mufutau","110-5516","Cherbourg-Octeville","P.O. Box 418, 4681 Eu Rd.","Bosnia and Herzegovina");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (438,"Price","Owen","1-112-174-8033","Margate","Ap #167-3969 Massa. Rd.","Turkmenistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (439,"Mathis","Barclay","1-268-345-9598","Lacombe County","1070 Tincidunt Road","South Georgia and The South Sandwich Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (440,"Noble","Joelle","749-4614","Wałbrzych","3729 Neque Rd.","South Africa");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (441,"Pearson","Cynthia","235-3609","Villa Alegre","Ap #869-2213 Justo. Av.","Qatar");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (442,"Lynn","Demetria","1-672-940-2627","Osgoode","P.O. Box 546, 1302 Sed Rd.","Togo");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (443,"Gentry","Owen","1-709-504-5125","Lichfield","Ap #429-8058 Quis Street","Liberia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (444,"Fischer","Keiko","468-3270","Çeşme","1725 Tortor Street","Mongolia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (445,"Strong","Lydia","503-2506","Ikot Ekpene","256-2978 Tellus. Rd.","Yemen");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (446,"Sullivan","Aspen","1-355-127-4767","Notre-Dame-de-la-Salette","157-3780 Ut Rd.","Guadeloupe");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (447,"Walsh","Cheyenne","114-9016","Kingston-on-Thames","Ap #534-9992 Magna. St.","South Africa");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (448,"Patton","Harriet","582-2999","Ceranesi","Ap #682-2368 Et Rd.","American Samoa");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (449,"Bridges","Ruth","787-8390","Walhain-Saint-Paul","Ap #894-3167 Fringilla Av.","Iceland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (450,"Fox","Minerva","1-908-740-2509","Panipat","783-8254 Hendrerit St.","Indonesia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (451,"English","Avram","215-8093","Worthing","756-4926 Cursus. Road","Grenada");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (452,"Collier","Asher","643-4809","Shaki","P.O. Box 443, 8346 Auctor. Ave","Guatemala");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (453,"Clark","Jerry","1-805-544-1260","Créteil","4209 Amet Ave","Greenland");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (454,"Lee","Penelope","1-630-957-3719","Fort Simpson","4913 Auctor St.","Macedonia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (455,"Beasley","Ariel","600-9184","Cap-de-la-Madeleine","Ap #911-9531 Semper. Street","Colombia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (456,"Oliver","Murphy","775-4240","Gespeg","Ap #168-2962 Commodo Rd.","Monaco");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (457,"Garcia","Linus","342-3637","Sint-Katherina-Lombeek","134-8638 Arcu. Av.","Cameroon");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (458,"Chavez","Violet","359-5455","Knokke","Ap #384-5311 Duis Avenue","Sudan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (459,"Riggs","Iris","603-0991","Castellana Sicula","6877 Felis Road","Greece");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (460,"Davenport","Hiroko","1-652-492-5082","Wambeek","Ap #243-8207 Quis Ave","Pitcairn Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (461,"Stevens","Denise","1-447-178-1574","Kampenhout","785 Mi Street","Maldives");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (462,"Tate","Aristotle","892-3648","Luton","Ap #282-3482 A, Av.","Montserrat");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (463,"Key","Joel","777-6258","Peutie","3608 Nisl. Ave","Cambodia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (464,"Clayton","Adena","1-572-332-7669","Cleveland","P.O. Box 175, 8724 Adipiscing St.","Uganda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (465,"Petty","Rahim","719-8982","Birmingham","262-3906 Est St.","Norway");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (466,"Mcknight","Robin","1-876-136-5493","Minna","926-8418 Ut St.","Saint Barthélemy");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (467,"Browning","Sopoline","1-114-406-2298","Almelo","P.O. Box 795, 9395 Interdum. Road","Bahrain");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (468,"Riddle","Maggy","1-366-298-1428","María Elena","Ap #785-2330 Molestie St.","Uzbekistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (469,"Velazquez","Baker","544-2762","Latisana","458-9686 Enim Rd.","Colombia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (470,"Mooney","Marsden","565-1236","Buren","5205 Ipsum Av.","Turkmenistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (471,"Roman","Adria","410-8852","Longaví","Ap #155-6387 Magna, Rd.","Estonia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (472,"Shelton","Hammett","1-701-545-4569","Beaumaris","183-4453 Vitae Road","Albania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (473,"Hernandez","Olga","1-475-919-0439","Matagami","5445 Nam Avenue","Antarctica");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (474,"Hernandez","Teegan","696-2658","Basirhat","P.O. Box 342, 9843 Rhoncus. Rd.","Namibia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (475,"Blair","Macey","1-293-492-0066","Halisahar","Ap #373-5156 Interdum St.","Portugal");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (476,"Odonnell","Dillon","803-6740","Talcahuano","9084 Adipiscing. Street","Bonaire, Sint Eustatius and Saba");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (477,"Cabrera","Julie","1-270-299-3714","Oliver","P.O. Box 368, 8572 Dignissim Road","Norfolk Island");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (478,"Mcbride","Sigourney","1-735-561-3675","Malahide","951-159 Dolor, Rd.","Timor-Leste");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (479,"Pugh","Cody","380-2643","Porto Cesareo","P.O. Box 319, 905 Justo Rd.","Vanuatu");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (480,"Wells","Haley","1-299-979-0977","Rouvreux","7851 Semper Street","Croatia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (481,"Hanson","Keane","244-3170","Wolvertem","3953 Nam St.","Niue");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (482,"Chandler","Mufutau","426-3673","Tamworth","P.O. Box 420, 4001 Non St.","Mauritius");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (483,"Watts","Jarrod","768-1850","Sens","P.O. Box 750, 1005 Curabitur Av.","Germany");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (484,"Yang","Nerea","383-0804","New Haven","754-1168 Non, Road","Sao Tome and Principe");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (485,"Barnett","Nevada","714-7765","B.S.D.","6654 Nisl Road","Colombia");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (486,"Vance","Amal","1-971-287-8990","Bismil","P.O. Box 948, 483 Accumsan Street","Brazil");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (487,"Stanley","Clinton","1-468-366-4964","Fontaine-Valmont","4426 Ullamcorper Street","Uganda");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (488,"Nixon","Kiara","1-999-252-4742","Pessac","Ap #905-8640 Ipsum Road","United States");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (489,"Britt","Lara","1-661-295-8472","Bingen","Ap #674-2934 Sagittis Avenue","Albania");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (490,"Todd","Fritz","809-6782","Thurso","Ap #768-1223 Erat Ave","Ukraine");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (491,"Shelton","Aline","1-835-164-5057","Giugliano in Campania","317-8884 Convallis St.","Saint Vincent and The Grenadines");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (492,"Buchanan","James","1-419-648-5778","Richmond Hill","534-5530 A Rd.","Svalbard and Jan Mayen Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (493,"Schneider","Stacey","1-161-767-5445","Alert Bay","P.O. Box 828, 5112 Orci Street","Czech Republic");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (494,"Brewer","Abel","774-6733","Anchorage","P.O. Box 639, 2736 Ullamcorper, St.","Isle of Man");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (495,"Sharp","Branden","334-7878","Carovilli","Ap #299-7444 Proin Street","Gibraltar");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (496,"Sexton","Armand","580-3563","San Pablo","P.O. Box 616, 8033 Luctus Ave","Afghanistan");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (497,"Short","Isabelle","1-405-486-5021","Omal","P.O. Box 848, 7980 Interdum Ave","Åland Islands");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (498,"Levy","Chase","1-887-433-5840","Milwaukee","6165 Lacus. Ave","Sweden");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (499,"Gentry","Ashton","1-666-863-8144","Linkebeek","P.O. Box 309, 6397 Pretium Av.","Botswana");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (500,"Rivas","Amery","1-321-875-0986","Freux","Ap #225-6988 Nunc Avenue","Aruba");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (501, "Amarasiri", "Evanthika", "+94773636352", "Galle Road", "Colombo 03", "Sri Lanka");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (502, "Fernando", "Senaka", "+94777112987", "Je-ela", "Temple Road", "Sri Lanka");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (503, "Hiranya", "Hasitha", "+94771222922", "Kandy", "Radella", "Sri Lanka");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (504, "Madurangi", "Pavithra", "+94772331922", "Horana", "6th Street", "Sri Lanka");
INSERT INTO `patient` (`number`,`last_name`,`first_name`,`phone`,`city`,`street`,`country`) VALUES (505, "Anuradha", "Chamara", "+94773113871", "Kegalle", "5th Lane", "Sri Lanka");